# 0 Imports

In [48]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

import pandas as pd

from src.suporte import funcoes_suporte as fs

## 0.1 Funções Suporte

In [49]:
fs.jupyter_settings(altura = 10, largura = 12, fonte = 8)
fs.supressao_notacao(casa_decimal = 2)

# 0.2 Load Data

In [50]:
df_raw = pd.read_csv('../data/raw/data.csv', encoding_errors="replace")
df_raw.sample(5)

       InvoiceNo StockCode               Description  Quantity       InvoiceDate  UnitPrice  CustomerID         Country
510147    579430     22633    HAND WARMER UNION JACK         2  11/29/2011 13:06       2.10    12748.00  United Kingdom
320805    565114     22492   MINI PAINT SET VINTAGE         36    9/1/2011 11:15       0.65    13588.00  United Kingdom
362812    568526     20996  JAZZ HEARTS ADDRESS BOOK        24   9/27/2011 13:04       0.19    17656.00  United Kingdom
440968    574555    51014L    FEATHER PEN,LIGHT PINK        12   11/4/2011 15:29       0.39    16426.00  United Kingdom
535279    581194     22190            LOCAL CAFE MUG        24   12/7/2011 17:17       0.39    15298.00  United Kingdom

# 1.0 Descrição dos Dados

## 1.1 Rename Columns

In [51]:
df_raw.columns = [fs.to_snake_case(col) for col in df_raw.columns]
df_raw.head()

  invoice_no stock_code                          description  quantity    invoice_date  unit_price  customer_id         country
0     536365     85123A   WHITE HANGING HEART T-LIGHT HOLDER         6  12/1/2010 8:26        2.55     17850.00  United Kingdom
1     536365      71053                  WHITE METAL LANTERN         6  12/1/2010 8:26        3.39     17850.00  United Kingdom
2     536365     84406B       CREAM CUPID HEARTS COAT HANGER         8  12/1/2010 8:26        2.75     17850.00  United Kingdom
3     536365     84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6  12/1/2010 8:26        3.39     17850.00  United Kingdom
4     536365     84029E       RED WOOLLY HOTTIE WHITE HEART.         6  12/1/2010 8:26        3.39     17850.00  United Kingdom

## 1.2 Data Info

In [52]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   invoice_no    541909 non-null  str
 1   stock_code    541909 non-null  str
 2   description   540455 non-null  str
 3   quantity      541909 non-null  int64
 4   invoice_date  541909 non-null  str
 5   unit_price    541909 non-null  float64
 6   customer_id   406829 non-null  float64
 7   country       541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

### 1.2.1 NA

In [53]:
df_raw.isna().sum()

invoice_no           0
stock_code           0
description       1454
quantity             0
invoice_date         0
unit_price           0
customer_id     135080
country              0
dtype: int64

In [54]:
df_raw = df_raw.dropna(subset=["description", "customer_id"])

## 1.3 Change Dtypes

In [58]:
df_raw["invoice_date"] = pd.to_datetime(df_raw["invoice_date"], format="%m/%d/%Y %H:%M").dt.normalize()

df_raw['customer_id'] = df_raw['customer_id'].astype(int)
df_raw.sample()

       invoice_no stock_code                     description  quantity invoice_date  unit_price  customer_id         country
202586     554487      21524  DOORMAT SPOTTY HOME SWEET HOME         1   2011-05-24        7.95        16919  United Kingdom

In [59]:
df_raw.dtypes

invoice_no                 str
stock_code                 str
description                str
quantity                 int64
invoice_date    datetime64[us]
unit_price             float64
customer_id              int64
country                    str
dtype: object

## 1.4 Estatística Descritiva Simples

# 2.0 Exportar DF

In [60]:
path = "../data/interim/1.descricao.pkl"
fs.save_pickle(obj=df_raw, path=path)