# 0 Imports

In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

import re

import pandas as pd

from src.suporte import funcoes_suporte as fs

## 0.1 Funções Suporte

In [2]:
fs.jupyter_settings(altura = 10, largura = 12, fonte = 8)
fs.supressao_notacao(casa_decimal = 2)

# 0.2 Load Data

In [3]:
df = fs.load_pickle('../data/interim/1.descricao.pkl')
df.sample(5)

       invoice_no stock_code                          description  quantity invoice_date  unit_price  customer_id         country
394974     570910      23250        VINTAGE RED TRIM ENAMEL BOWL         12   2011-10-13        1.25        15489  United Kingdom
359294     568185      23156        SET OF 5 MINI GROCERY MAGNETS         1   2011-09-25        2.08        16594  United Kingdom
355933     567980      22620          4 TRADITIONAL SPINNING TOPS         3   2011-09-23        1.45        15311  United Kingdom
207558     554993      21213          PACK OF 72 SKULL CAKE CASES        12   2011-05-29        0.55        17051  United Kingdom
14527     C537602      22061  LARGE CAKE STAND  HANGING STRAWBERY        -1   2010-12-07        8.50        17511  United Kingdom

# 1.0 Tratamento

## 1.1 Numerico

### 1.1.1 unit_price

In [4]:
df = df.loc[df['unit_price'] >= 0.010,:]

## 1.2 Categórico

1.2.1 stock_code

In [5]:
df = df.loc[~(df['stock_code'].isin(['POST', 'D', 'C2', 'M', 'BANK CHARGES', 'PADS', 'DOT', 'CRUK']))]

### 1.2.2. quantity

In [6]:
df_returns = df.loc[df['quantity'] < 0,:]
df_compras = df.loc[df['quantity'] > 0,:]

In [7]:
df.head()

  invoice_no stock_code                          description  quantity invoice_date  unit_price  customer_id         country
0     536365     85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   2010-12-01        2.55        17850  United Kingdom
1     536365      71053                  WHITE METAL LANTERN         6   2010-12-01        3.39        17850  United Kingdom
2     536365     84406B       CREAM CUPID HEARTS COAT HANGER         8   2010-12-01        2.75        17850  United Kingdom
3     536365     84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   2010-12-01        3.39        17850  United Kingdom
4     536365     84029E       RED WOOLLY HOTTIE WHITE HEART.         6   2010-12-01        3.39        17850  United Kingdom

# 2.0 Export DF

In [8]:
fs.save_pickle(df,"../data/interim/2.all_quantity.pkl")
fs.save_pickle(df_returns,"../data/interim/2.df_returns.pkl")
fs.save_pickle(df_compras,"../data/interim/2.df_compras.pkl")