# 0 Imports

In [7]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

import pandas as pd

from src.suporte import funcoes_suporte as fs

from sklearn import preprocessing as pp

## 0.1 Funções Suporte

In [5]:
fs.jupyter_settings(altura = 10, largura = 12, fonte = 8)
fs.supressao_notacao(casa_decimal = 2)

# 0.2 Load Data

In [14]:
df = fs.load_pickle("../data/interim/3.fe.pkl")
df.sample(5)

      customer_id  faturamento  recencia_days  frequencia  avg_faturamento  retornos
941         17707       152.40            185           2            30.48      0.00
1102        12356      2487.43             22           3            42.89      0.00
2316        15135       139.05            239           1            15.45      1.00
1611        14880       706.19             77           3            15.03      0.00
250         13269      5346.23              1          15            16.92      2.00

In [15]:
df.columns

Index(['customer_id', 'faturamento', 'recencia_days', 'frequencia',
       'avg_faturamento', 'retornos'],
      dtype='object')

# 1.0 Encoders

# 2.0 Reescala

In [16]:
mms = pp.MinMaxScaler()

for col in df.columns:
    if not(col == 'customer_id'):
        df[col] = mms.fit_transform(df[[col]])

In [17]:
df.head()

   customer_id  faturamento  recencia_days  frequencia  avg_faturamento  retornos
0        17850         0.02           1.00        0.16             0.00      0.02
1        13047         0.01           0.15        0.04             0.00      0.16
2        12583         0.02           0.01        0.07             0.00      0.04
3        13748         0.00           0.25        0.02             0.00      0.00
4        15100         0.00           0.89        0.01             0.00      0.07

# 3.0 Exportar DF

In [18]:
fs.save_pickle(df,'../data/interim/5.data_prep.pkl')