# 0 Imports

In [24]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

import pandas as pd

from matplotlib import pyplot as plt

from sklearn.cluster import KMeans
from sklearn import metrics as m

from src.suporte import funcoes_suporte as fs

## 0.1 Funções Suporte

In [25]:
fs.jupyter_settings(altura = 16, largura = 8, fonte = 8)
fs.supressao_notacao(casa_decimal = 2)

# 0.2 Load Data

In [26]:
df = fs.load_pickle('../data/interim/7.data-k-definition.pkl')
df.sample(5)

      faturamento  recencia_days  frequencia  avg_faturamento
64         363.60            372           2           363.60
3468       659.44             85           1           659.44
4256       161.67             17           1           161.67
378        426.79            310           2           426.79
4343       389.84              5           1           389.84

# 1.0 Modelo

## 1.1 KMean

In [27]:
K = 4
kmeans = KMeans( init='random', n_clusters=K, n_init=10, max_iter=100, random_state=88)

kmeans.fit(df)

labels = kmeans.labels_

### 1.1.1 Métricas

#### 1.1.1.1 WSS

In [28]:
kmeans.inertia_

79930757530.28392

#### 1.1.1.2 SS

In [29]:
m.silhouette_score(df, labels, metric='euclidean')

0.8162625895105571

# 2.0 Exportar Modelo

In [30]:
df_cluster = fs.load_pickle("../data/interim/2.fe.pkl")

In [31]:
df_cluster['clusters'] = labels
df_cluster

      customer_id  faturamento  recencia_days  frequencia  avg_faturamento  clusters
0           17850      5288.63            302          35          5288.63         3
1           13047      3079.10             31          18          3079.10         1
2           12583      7187.34              2          18          7187.34         3
3           13748       948.25             95           5           948.25         1
4           15100       635.10            330           6           635.10         1
5           15291      4596.51             25          20          4596.51         3
6           14688      5107.38              7          27          5107.38         3
7           17809      4627.62             16          15          4627.62         3
8           15311     59419.34              0         118         59419.34         2
9           14527      7711.38              2          86          7711.38         3
10          16098      2005.63             87           7          2005.63         1
11          18074       489.60            373           1           489.60         1
12          17420       598.83             50           3           598.83         1
13          16029     50992.61             38          76         50992.61         2
14          16250       389.44            261           2           389.44         1
15          12431      6416.39             35          18          6416.39         3
16          17511     88125.38              2          46         88125.38         2
17          17548      -141.48            217           3          -141.48         1
18          13705       711.86              7           3           711.86         1
19          13747        79.60            373           1            79.60         1
20          13408     27487.41              1          81         27487.41         2
21          13767     16945.71              2          52         16945.71         3
22          17924      2894.33              1          13          2894.33         1
23          13448      3465.67             16          10          3465.67         1
24          15862       832.88              8           4           832.88         1
25          15513     14520.08             31          22         14520.08         3
26          12791       192.60            373           1           192.60         1
27          16218      3054.87             29           8          3054.87         1
28          14045      1659.75            109           4          1659.75         1
29          14307      2995.72             88           6          2995.72         1
30          17908       243.28            373           1           243.28         1
31          17920      4204.10              4          17          4204.10         1
32          12838       683.13             33           2           683.13         1
33          13255       390.66              3           3           390.66         1
34          16583       233.45            373           1           233.45         1
35          18085       689.95            330           2           689.95         1
36          13758      3190.55             11           7          3190.55         1
37          13694     62653.10              3          60         62653.10         2
38          15983      1475.02             22           4          1475.02         1
39          14849      7904.28             21          28          7904.28         3
40          17968       277.35            373           1           277.35         1
41          16210     21086.30              1          18         21086.30         3
42          17897       541.10            172           4           541.10         1
43          17377      3925.92             23          21          3925.92         1
44          16552       379.73            242           2           379.73         1
45          17181       239.92             57           2           239.92         1
46          17951       990.84             39           4           990.84         1
47          14729       313.49            373           1           313.49         1
48          12748     29072.10              0         224         29072.10         2
49          15012       423.04             53           2           423.04         1
50          12868      1607.06            185           6          1607.06         1
51          17572       226.75             71           4           226.75         1
52          14078      1049.37            101           6          1049.37         1
53          14001      2030.33             45           4          2030.33         1
54          12662      3817.08              0          12          3817.08         1
55          15525       811.02              2           4           811.02         1
56          14237       161.00            373           1           161.00         1
57          17905       800.24             71           4           800.24         1
58          15485      2575.00             30           3          2575.00         1
59          12433     13375.87              0           7         13375.87         3
60          16955       493.67            184           5           493.67         1
61          15350       115.65            373           1           115.65         1
62          15605      1198.23             36           5          1198.23         1
63          18144      2888.75              7          12          2888.75         1
64          15922       363.60            372           2           363.60         1
65          14594       379.83              7           2           379.83         1
66          15165       487.75            373           1           487.75         1
67          14911    132572.62              1         248        132572.62         0
68          16456      2158.37             99           5          2158.37         1
69          17841     40340.78              1         169         40340.78         2
70          12472      6229.48             30          13          6229.48         3
71          17346      2611.58              3          16          2611.58         1
72          17643       101.55            373           1           101.55         1
73          17873      1764.36             80           6          1764.36         1
74          13093      7741.47            267          13          7741.47         3
75          12921     16389.74              3          50         16389.74         3
76          13468      5656.75              1          41          5656.75         3
77          17760       287.59             21           2           287.59         1
78          16928      2781.50             80          19          2781.50         1
79          16048       243.69             85           3           243.69         1
80          16274       357.95            373           1           357.95         1
81          14496       538.81            311           2           538.81         1
82          14696      2070.97              4           9          2070.97         1
83          16539      1388.81              2           4          1388.81         1
84          17025       357.77             60           3           357.77         1
85          13777     25748.35              0          41         25748.35         2
86          17690      4748.45             30          16          4748.45         3
87          12947      1407.29            143          11          1407.29         1
88          17460       452.63             78           8           452.63         1
89          18229      7276.90             11          20          7276.90         3
90          14142       311.81            373           1           311.81         1
91          17069      2655.22             28          13          2655.22         1
92          13065       205.86            373           1           205.86         1
93          14606     11713.85              1         128         11713.85         3
94          16835       180.85            128           2           180.85         1
95          15235      2247.51            217          12          2247.51         1
96          13576      6703.30             10          20          6703.30         3
97          18011       102.79            373           1           102.79         1
98          13090      8689.39              8          18          8689.39         3
99          15694      6423.60              0          15          6423.60         3
100         14741      1400.34             11           6          1400.34         1
101         13715      1053.94            281           8          1053.94         1
102         14092      4063.10              7          17          4063.10         1
103         17732       303.97            372           1           303.97         1
104         12855        38.10            372           1            38.10         1
105         15752      2628.93             39           8          2628.93         1
106         17855       208.97            372           1           208.97         1
107         14047      1290.01              8           7          1290.01         1
108         17925       244.08            372           1           244.08         1
109         13941      4912.41             21           7          4912.41         3
110         17017      8574.11              2          27          8574.11         3
111         14135      4690.31              1          15          4690.31         3
112         13108       350.06            372           1           350.06         1
113         12471     18740.92              2          49         18740.92         3
114         15601      6745.36             11          17          6745.36         3
115         13418      5845.44             11          23          5845.44         3
116         14766      2423.07              8           8          2423.07         1
117         15658       958.90            190           8           958.90         1
118         14388      3172.04              8          10          3172.04         1
119         14901      1414.99             11          10          1414.99         1
120         18041      4161.14             11          22          4161.14         1
121         15955      4389.81             24          16          4389.81         1
122         15070       106.20            372           1           106.20         1
123         16244      1522.75            211           2          1522.75         1
124         15111      1567.48             29           3          1567.48         1
125         14390      4592.47             10          13          4592.47         3
126         16546       -95.93            290           3           -95.93         1
127         15260      1780.77            100           8          1780.77         1
128         13305      2000.86              4          10          2000.86         1
129         14491       340.93            175           2           340.93         1
130         14060      6135.38              4          20          6135.38         3
131         15923       127.08            372           1           127.08         1
132         16752       207.50            372           1           207.50         1
133         17287      1064.11             26           7          1064.11         1
134         15363       318.05            241           2           318.05         1
135         12915       363.65            148           2           363.65         1
136         15544      3542.51              8          11          3542.51         1
137         15738      4788.77             18          19          4788.77         3
138         16042      1147.37             22           7          1147.37         1
139         17381     20272.43              8          30         20272.43         3
140         15827      1641.48             73          20          1641.48         1
141         14180      4640.77             10          31          4640.77         3
142         13117       984.91             21           8           984.91         1
143         16916       576.26             23           2           576.26         1
144         17964       471.70             31           2           471.70         1
145         14466      2272.40             29           7          2272.40         1
146         17235       550.06             25           2           550.06         1
147         16510       248.10            372           1           248.10         1
148         17802      1251.84             82           4          1251.84         1
149         15107       247.66            311           8           247.66         1
150         17976       353.19            372           1           353.19         1
151         14449       907.10             18           4           907.10         1
152         15838     33350.76             11          21         33350.76         2
153         16781       294.65            365           2           294.65         1
154         17547       -11.80            372           1           -11.80         1
155         13491      1215.82             51          10          1215.82         1
156         16186      3991.94             22          13          3991.94         1
157         17685      3191.53             16           7          3191.53         1
158         17581     10736.11              0          31         10736.11         3
159         15732       294.12            212           2           294.12         1
160         13138       962.39             22           6           962.39         1
161         15823      -840.76            337           2          -840.76         1
162         17567      4012.56              7          10          4012.56         1
163         15061     54228.74              3          55         54228.74         2
164         16203       589.15             58           5           589.15         1
165         15640     12433.34              4          17         12433.34         3
166         15574       702.25            177           4           702.25         1
167         16770       744.90             57           6           744.90         1
168         17838      2312.70             26           6          2312.70         1
169         17228      1906.09             15           8          1906.09         1
170         14829       644.65             29           6           644.65         1
171         17412      1258.06              2           7          1258.06         1
172         14031     14634.64              7          23         14634.64         3
173         14775      1011.90             58           3          1011.90         1
174         12971     10930.26              3          89         10930.26         3
175         15834      2084.90             70           6          2084.90         1
176         17659      2954.75              3          14          2954.75         1
177         15299      3787.09             67          11          3787.09         1
178         15646       425.14            157           4           425.14         1
179         13958      -102.45            372           1          -102.45         1
180         14443      1400.88             53           7          1400.88         1
181         14156    113384.14              9          66        113384.14         0
182         16995        -1.25            372           1            -1.25         1
183         13402       621.23            127           2           621.23         1
184         18168      1133.64            176           9          1133.64         1
185         17757      5585.49              1          31          5585.49         3
186         14625       848.48            185           5           848.48         1
187         13011        50.55            372           1            50.55         1
188         13798     36351.42              1          63         36351.42         2
189         15384       635.76            169           3           635.76         1
190         14264       319.47            154           3           319.47         1
191         13295       197.95            359           2           197.95         1
192         16754      2002.40            372           1          2002.40         1
193         16634       217.90            222           2           217.90         1
194         18239      1561.61            218           5          1561.61         1
195         14576        35.40            372           1            35.40         1
196         13145       614.77             39           5           614.77         1
197         14395      3471.91              2          12          3471.91         1
198         14865        52.20              7           2            52.20         1
199         15093      4410.14             18           9          4410.14         1
200         12738       155.35            372           1           155.35         1
201         16150      1906.07             38          10          1906.07         1
202         17552       909.96             42           6           909.96         1
203         14236       490.86             80           2           490.86         1
204         17961      1296.44             21          39          1296.44         1
205         14573      1603.72            179          13          1603.72         1
206         17135      1139.73             16           7          1139.73         1
207         17396      7330.80             39           8          7330.80         3
208         14213     -1192.20            371           1         -1192.20         1
209         12967      1194.75              3           4          1194.75         1
210         12686        89.14            371           1            89.14         1
211         14679        -2.55            371           1            -2.55         1
212         15240      1685.57             44           7          1685.57         1
213         18225      5361.02              3          17          5361.02         3
214         13370       721.32            366           2           721.32         1
215         16883       276.73            187           2           276.73         1
216         13520      3487.75             58           8          3487.75         1
217         12841      3876.40              4          26          3876.40         1
218         16905      3085.48              5           8          3085.48         1
219         12427       708.37             11           5           708.37         1
220         17967       123.07            371           1           123.07         1
221         16891       809.70              1           5           809.70         1
222         14589        39.75            371           1            39.75         1
223         14680     26932.34             25          23         26932.34         2
224         17884       717.45              3           4           717.45         1
225         12557     11990.96             16           5         11990.96         3
226         14083      1018.43              4           9          1018.43         1
227         13013      4786.99              1          15          4786.99         3
228         14210      1900.89             91           7          1900.89         1
229         16477      2494.46             63           7          2494.46         1
230         12600      2581.04             28          11          2581.04         1
231         16013     33366.25              3          54         33366.25         2
232         17949     52750.84              1          52         52750.84         2
233         12779      3868.70             21          12          3868.70         1

In [32]:
fs.save_pickle(df_cluster,'../data/processed/8.data_model_training.pkl')
fs.save_pickle(kmeans,'../models/8.model_training.pkl' )