# 0 Imports

In [10]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

import pandas as pd

from matplotlib import pyplot as plt

from sklearn.cluster import KMeans
from sklearn import metrics as m

from src.suporte import funcoes_suporte as fs

## 0.1 Funções Suporte

In [11]:
fs.jupyter_settings(altura = 16, largura = 8, fonte = 8)
fs.supressao_notacao(casa_decimal = 2)

# 0.2 Load Data

In [12]:
df = fs.load_pickle('../data/interim/7.data-k-definition.pkl')
df.sample(5)

      faturamento  recencia_days  frequencia  avg_faturamento  retornos
760         -0.19           0.90       -0.35            -0.04     -0.50
1640        -0.22           1.08       -0.55            -0.03     -0.50
3727        -0.21          -0.39       -0.55            -0.04      0.11
620         -0.08          -0.74        0.40            -0.04     -0.50
2072         0.42          -0.94        0.76            -0.03      0.48

# 1.0 Modelo

## 1.1 KMean

In [13]:
K = 4
kmeans = KMeans( init='random', n_clusters=K, n_init=10, max_iter=100, random_state=42)

kmeans.fit(df)

labels = kmeans.labels_

### 1.1.1 Métricas

#### 1.1.1.1 WSS

In [14]:
kmeans.inertia_

1927.798529001194

#### 1.1.1.2 SS

In [15]:
m.silhouette_score(df, labels, metric='euclidean')

0.37991036793667415

# 2.0 Exportar Modelo

In [16]:
df_cluster = fs.load_pickle("../data/interim/3.fe.pkl")

In [17]:
df_cluster['clusters'] = labels
df_cluster.head()

   customer_id  faturamento  recencia_days  frequencia  avg_faturamento  retornos  clusters
0        17850      5391.21            372          34            18.15      1.00         3
1        13047      3232.59             56           9            18.90      7.00         1
2        12583      6705.38              2          15            28.90      2.00         1
3        13748       948.25             95           5            33.87      0.00         2
4        15100       876.00            333           3           292.00      3.00         3

In [18]:
fs.save_pickle(df_cluster,'../data/processed/8.data_model_training.pkl')
fs.save_pickle(kmeans,'../models/8.model_training.pkl' )