# 0 Imports

In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

import pandas as pd

from matplotlib import pyplot as plt

from sklearn.cluster import KMeans
from sklearn import metrics as m

from src.suporte import funcoes_suporte as fs

## 0.1 Funções Suporte

In [2]:
fs.jupyter_settings(altura = 16, largura = 8, fonte = 8)
fs.supressao_notacao(casa_decimal = 2)

# 0.2 Load Data

In [22]:
df = fs.load_pickle('../data/interim/7.data-k-definition.pkl')
df.sample(5)

      faturamento  recencia_days  qtde_compras  qtde_produto_comprado  avg_faturamento  avg_recency_days  frequencia  retornos
1445         0.01           0.08          0.00                   0.00             0.00              0.58        0.00      0.00
2265         0.00           0.53          0.00                   0.00             0.01              0.03        0.01      0.00
597          0.00           0.09          0.01                   0.00             0.00              0.26        0.00      0.00
1156         0.03           0.01          0.17                   0.01             0.00              0.02        0.01      0.24
3301         0.00           0.31          0.00                   0.00             0.00              0.17        0.00      0.00

# 1.0 Modelo

## 1.1 KMean

In [23]:
K = 5
kmeans = KMeans( init='random', n_clusters=K, n_init=10, max_iter=100, random_state=42)

kmeans.fit(df)

labels = kmeans.labels_

### 1.1.1 Métricas

#### 1.1.1.1 WSS

In [24]:
kmeans.inertia_

33.37807701864039

#### 1.1.1.2 SS

In [25]:
m.silhouette_score(df, labels, metric='euclidean')

0.3264354898958157

# 2.0 Exportar Modelo

In [26]:
df_cluster = fs.load_pickle("../data/interim/3.fe.pkl")

In [27]:
df_cluster['clusters'] = labels
df_cluster.head()

   customer_id  faturamento  recencia_days  qtde_compras  qtde_produto_comprado  avg_faturamento  avg_recency_days  frequencia  retornos  clusters
0        17850      5391.21            372            34                     35            18.15              1.00       17.00      1.00         2
1        13047      3232.59             56             9                    131            18.90             52.83        0.03      7.00         1
2        12583      6705.38              2            15                   1568            28.90             26.50        0.04      2.00         1
3        13748       948.25             95             5                    169            33.87             92.67        0.02      0.00         0
4        15100       876.00            333             3                     48           292.00             20.00        0.07      3.00         2

In [28]:
fs.save_pickle(df_cluster,'../data/processed/8.data_model_training.pkl')
fs.save_pickle(kmeans,'../models/8.model_training.pkl' )