# 0 Imports

In [1]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

import pandas as pd

from matplotlib import pyplot as plt

from sklearn.cluster import KMeans
from sklearn import metrics as m

from src.suporte import funcoes_suporte as fs

## 0.1 Funções Suporte

In [2]:
fs.jupyter_settings(altura = 16, largura = 8, fonte = 8)
fs.supressao_notacao(casa_decimal = 2)

# 0.2 Load Data

In [3]:
df = fs.load_pickle('../data/interim/7.data-k-definition.pkl')
df.sample(5)

      faturamento  recencia_days  frequencia  avg_faturamento  retornos
3847         0.00           0.13        0.00             0.00      0.02
979          0.01           0.02        0.03             0.00      0.00
4214         0.00           0.05        0.00             0.00      0.00
490          0.00           0.25        0.01             0.00      0.00
690          0.00           0.01        0.01             0.00      0.00

# 1.0 Modelo

## 1.1 KMean

In [4]:
K = 5
kmeans = KMeans( init='random', n_clusters=K, n_init=10, max_iter=100, random_state=42)

kmeans.fit(df)

labels = kmeans.labels_

### 1.1.1 Métricas

#### 1.1.1.1 WSS

In [5]:
kmeans.inertia_

30.11635803429747

#### 1.1.1.2 SS

In [6]:
m.silhouette_score(df, labels, metric='euclidean')

0.49896161861766664

# 2.0 Exportar Modelo

In [7]:
df_cluster = fs.load_pickle("../data/interim/3.fe.pkl")

In [8]:
df_cluster['clusters'] = labels
df_cluster

      customer_id  faturamento  recencia_days  frequencia  avg_faturamento  retornos  clusters
0           17850      5391.21            372          34            18.15      1.00         0
1           13047      3232.59             56           9            18.90      7.00         2
2           12583      6705.38              2          15            28.90      2.00         1
3           13748       948.25             95           5            33.87      0.00         2
4           15100       876.00            333           3           292.00      3.00         0
5           15291      4623.30             25          14            45.33      5.00         1
6           14688      5630.87              7          21            17.22      6.00         1
7           17809      5411.91             16          12            88.72      2.00         1
8           15311     60767.90              0          91            25.54     27.00         1
9           16098      2005.63             87           7            29.93      0.00         2
10          18074       489.60            373           1            37.66      0.00         0
11          17420       598.83             50           3            19.96      0.00         2
12          16029     72882.09             38          62           302.42      4.00         1
13          16250       389.44            261           2            16.23      0.00         4
14          12431      6382.45             35          15            27.39      3.00         1
15          17511     91062.38              2          31            94.56     14.00         1
16          13705       711.86              7           3            25.42      0.00         1
17          13747        79.60            373           1            79.60      0.00         0
18          13408     28117.04              1          62            58.82     13.00         1
19          13767     17220.36              2          37            46.79     15.00         1
20          17924      2962.50             11           7            95.56      6.00         1
21          13448      3539.37             16           6            18.15      4.00         1
22          15862       832.88              8           4             5.67      0.00         1
23          15513     14758.22             33          19            47.92      3.00         1
24          12791       177.60            373           1           177.60      0.00         0
25          16218      3084.68             29           7            36.72      1.00         1
26          14045      1659.75            109           4           276.62      0.00         2
27          14307      2995.72             88           6            16.64      0.00         2
28          17908       243.28            373           1             4.19      0.00         0
29          17920      4192.20              4          17             6.03      0.00         1
30          12838       683.13             33           2             5.55      0.00         1
31          13255       399.51              9           2            30.73      1.00         1
32          16583       233.45            373           1            16.68      0.00         0
33          18085       689.95            330           2            23.79      0.00         0
34          13758      3190.55             11           7            27.27      0.00         1
35          13694     65039.62              3          50           114.51      7.00         1
36          15983      1475.02             22           4            13.05      0.00         1
37          14849      7930.54             21          25            20.44      3.00         1
38          17968       277.35            373           1             3.26      0.00         0
39          16210     21076.30              1          17           172.76      0.00         1
40          17897       566.60            172           3             4.97      1.00         3
41          17377      4100.92             23          20             9.81      1.00         1
42          16552       379.73            242           2            22.34      0.00         4
43          17181       239.92             57           2            10.43      0.00         2
44          17951      1008.54             39           3            50.43      1.00         1
45          14729       313.49            373           1             4.42      0.00         0
46          12748     32317.32              0         206             7.06     11.00         1
47          15012       423.04             53           2             3.31      0.00         2
48          12868      1607.06            185           6            15.02      0.00         3
49          17572       226.75             71           4            18.90      0.00         2
50          14078      1049.37            101           6            16.14      0.00         2
51          14001      2043.08             45           3            52.39      0.00         2
52          12662      3543.78              0          11            16.11      1.00         1
53          15525       823.42              2           3             4.65      1.00         1
54          14237       161.00            373           1            17.89      0.00         0
55          17905       800.24             71           4            23.54      0.00         2
56          15485      2575.00             30           3            29.94      0.00         1
57          12433     13375.87              0           7            31.85      0.00         1
58          16955       518.67            184           4            20.75      1.00         3
59          15350       115.65            373           1            23.13      0.00         0
60          15605      1198.23             36           5            17.88      0.00         1
61          18144      2888.75              7          12            67.18      0.00         1
62          15922       369.50            373           1            33.59      1.00         0
63          14594       379.83              7           2             7.17      0.00         1
64          15165       487.75            373           1            18.06      0.00         0
65          14911    136275.72              1         198            24.38     44.00         1
66          16456      2158.37             99           5            19.44      0.00         2
67          17346      2676.56              3          15             5.35      1.00         1
68          17643       101.55            373           1            12.69      0.00         0
69          17841     40967.72              1         124             5.23     45.00         1
70          17873      1729.78             80           5            40.23      1.00         2
71          13093      7832.47            275           8            49.26      5.00         4
72          12921     16587.09              9          37            23.04     13.00         1
73          13468      5704.97              1          37            18.89      4.00         1
74          17760       287.59             21           2            11.50      0.00         1
75          16928      2839.65             80          17            13.65      2.00         2
76          16048       256.44            373           2            32.05      1.00         0
77          16274       337.75            373           1             5.20      0.00         0
78          14496       538.81            311           2            28.36      0.00         0
79          14696      2078.95              4           7            15.99      2.00         1
80          16539      1388.81              2           4            30.86      0.00         1
81          17025       357.77             60           3            39.75      0.00         2
82          13777     25977.16              0          33           131.86      7.00         1
83          17690      4757.95             30          15            18.59      1.00         1
84          12947      1603.99            143           6            16.54      5.00         3
85          17460       622.43             94           6            21.46      2.00         2
86          18229      7276.90             11          20            44.37      0.00         1
87          14142       311.81            373           1            14.17      0.00         0
88          17069      2709.70             28           9            18.95      4.00         1
89          13065       205.86            373           1            14.70      0.00         0
90          14606     12006.65              1          90             4.45     35.00         1
91          16835       180.85            128           2            18.09      0.00         3
92          15235      2247.51            217          12            15.72      0.00         4
93          13576      6717.34             10          18            53.31      2.00         1
94          18011       102.79            373           1             3.67      0.00         0
95          13090      8895.82              8          13            57.77      4.00         1
96          15694      6464.40              0          13            83.95      1.00         1
97          14741      1400.34             11           6            23.73      0.00         1
98          13715      1079.34            281           5            10.28      3.00         4
99          17732       303.97            372           1            16.89      0.00         0
100         12855        38.10            372           1            12.70      0.00         0
101         15752      2637.38             39           7             6.42      1.00         1
102         17855       208.97            372           1            12.29      0.00         0
103         14047      1308.61              8           5            40.89      2.00         1
104         17925       244.08            372           1           244.08      0.00         0
105         13941      5112.96             21           5           113.62      2.00         1
106         17017      8694.26              2          20            34.50      7.00         1
107         14135      4690.31              1          15            35.00      0.00         1
108         13108       350.06            372           1            35.01      0.00         0
109         15601      6776.56             11          14            16.53      3.00         1
110         13418      6127.43             11          18            20.16      5.00         1
111         15658      1024.10            190           5            21.34      3.00         3
112         14388      3212.84             10           8            17.27      2.00         1
113         14901      1421.29             11           9            14.81      1.00         1
114         18041      4183.39             11          21             8.86      1.00         1
115         15955      4416.26             24          14            24.13      2.00         1
116         15070       106.20            372           1           106.20      0.00         0
117         16244      1522.75            211           2            16.73      0.00         4
118         15111      1567.48             29           3            18.66      0.00         1
119         14390      4652.82             10           9            16.27      4.00         1
120         16546       787.15            290           2            31.49      1.00         4
121         15260      1810.77            100           7            23.52      1.00         2
122         13305      2000.86              4          10            24.70      0.00         1
123         14491       340.93            175           2            20.05      0.00         3
124         14060      6140.42              4          19            30.40      1.00         1
125         15923       127.08            372           1             6.05      0.00         0
126         16752       207.50            372           1            23.06      0.00         0
127         17287      1064.11             26           7             8.58      0.00         1
128         15363       326.00            372           1            20.38      1.00         0
129         12915       363.65            148           2            16.53      0.00         3
130         15544      3546.71              9           9            13.69      2.00         1
131         15738      4812.42             18          16            27.82      3.00         1
132         17381     20275.61              8          29           186.01      1.00         1
133         15827      1836.09             73          14            15.97      6.00         2
134         14180      4748.52             10          25            19.79      6.00         1
135         13117       984.91             21           8            12.96      0.00         1
136         16916       576.26             23           2             4.03      0.00         1
137         17964       471.70             31           2             4.54      0.00         1
138         14466      2272.40             29           7            31.56      0.00         1
139         17235       550.06             25           2            18.97      0.00         1
140         16510       248.10            372           1            19.08      0.00         0
141         17802      1285.04             82           3             9.18      1.00         2
142         15107       319.50            311           6            19.97      2.00         0
143         17976       353.19            372           1             5.43      0.00         0
144         14449       907.10             18           4             3.52      0.00         1
145         16781       311.25            372           1            18.31      1.00         0
146         13491      1215.82             51          10            14.14      0.00         2
147         16186      4006.94             22          12            18.38      1.00         1
148         17685      3191.53             16           7            24.55      0.00         1
149         17581     11045.04              0          25            25.10      6.00         1
150         15732       294.12            212           2            21.01      0.00         4
151         13138       962.39             22           6            15.28      0.00         1
152         17567      4331.48              7           8            26.25      2.00         1
153         15061     54534.14              3          48           135.32      6.00         1
154         16203       592.90             58           4            16.94      1.00         2
155         15640     12515.66              4          15            25.86      2.00         1
156         15574       702.25            177           4             4.18      0.00         3
157         16770       770.10             57           5             5.31      1.00         2
158         17838      2779.30             26           5            22.97      1.00         1
159         17228      1906.09             15           8             9.16      0.00         1
160         14829       697.55             29           4            16.61      2.00         1
161         17412      1258.06              2           7            19.06      0.00         1
162         14031     17286.86              7          19            69.15      3.00         1
163         14775      1011.90             58           3            16.86      0.00         2
164         12971     11189.91              3          86            36.69      2.00         1
165         17659      2999.46             17          12            18.98      2.00         1
166         15299      3907.01             67           6           651.17      1.00         2
167         15646       447.64            157           3            12.79      1.00         3
168         13402       621.23            127           2            15.93      0.00         3
169         17757      5601.34              1          30             7.57      1.00         1
170         13011        50.55            372           1            16.85      0.00         0
171         13798     37153.85              1          57           106.46      6.00         1
172         16754      2002.40            372           1          1001.20      0.00         0
173         16634       217.90            222           2            24.21      0.00         4
174         18239      1561.61            218           5            17.75      0.00         4
175         14576        35.40            372           1            35.40      0.00         0
176         13145       618.52             39           4           103.09      1.00         1
177         18168      1169.94            176           6             8.93      3.00         3
178         14395      3507.71              2           9            10.02      3.00         1
179         14865        52.20              7           2            13.05      0.00         1
180         15093      4597.02             18           6            42.57      3.00         1
181         12738       137.35            372           1            13.73      0.00         0
182         16150      2053.02             42           5            17.55      5.00         1
183         17552       930.41             60           4            18.99      1.00         2
184         14236       490.86             80           2            32.72      0.00         2
185         17961      1296.44             21          39             5.21      0.00         1
186         14573      1653.42            179           9             7.04      4.00         3
187         17135      1139.73             16           7            21.92      0.00         1
188         17396      7312.80             39           7           281.26      0.00         1
189         12967      1660.90            358           2            87.42      2.00         0
190         12686        71.14            371           1            11.86      0.00         0
191         13370       754.87            371           1            19.36      1.00         0
192         16883       276.73            187           2             7.28      0.00         3
193         13520      2984.35             58           6            34.30      1.00         2
194         12841      4022.35              4          25             9.58      1.00         1
195         16905      3102.43              5           7            14.92      1.00         1
196         12427       699.80             21           3            24.99      2.00         1
197         17967       123.07            371           1             2.56      0.00         0
198         16891       809.70              1           5             3.99      0.00         1
199         14589        39.75            371           1            13.25      0.00         0
200         14156    116729.63              9          54            84.16     10.00         1
201         14680     28754.11             25          16           111.45      7.00         1
202         17884       717.45              3           4             6.13      0.00         1
203         12557     11990.96             16           5           363.36      0.00         1
204         14083      1018.43              4           9             5.63      0.00         1
205         13013      4810.94              1          13            21.97      2.00         1
206         14210      1905.84            105           6            18.68      1.00         2
207         16477      2494.46             63           7            17.09      0.00         2
208         12600      2311.04             28          10            42.80      0.00         1

In [9]:
fs.save_pickle(df_cluster,'../data/processed/8.data_model_training.pkl')
fs.save_pickle(kmeans,'../models/8.model_training.pkl' )