# 0 Imports

In [4]:
import sys
import os
sys.path.insert(0, os.path.abspath('..'))

import pandas as pd

import plotly.express as px

from sklearn.cluster import KMeans
from sklearn import metrics as m

from src.suporte import funcoes_suporte as fs

## 0.1 Funções Suporte

In [7]:
fs.jupyter_settings(altura = 16, largura = 12, fonte = 8)
fs.supressao_notacao(casa_decimal = 2)

# 0.2 Load Data

In [5]:
df = fs.load_pickle("../data/processed/8.model_training.pkl")
df.sample(5)

      customer_id  faturamento  recencia_days  invoice_no  clusters
1560        14477      1307.81             19           5         1
2375        13952      3246.09            211           3         1
1078        15569      1375.71            103           5         1
1850        16242      3598.26              8           8         1
3626        18192       957.97             71           1         1

# 1. Análise

## 1.1. Visualizações

In [8]:
fig = px.scatter_3d(df, x='recencia_days', y='invoice_no', z='faturamento', color='clusters')
fig.show()

## 1.2. Cluster Profile

In [14]:
# Numero de Pessoas
df_cluster = df[['customer_id', 'clusters']].groupby('clusters').count().reset_index()
df_cluster['perc_customer'] = 100*(df_cluster['customer_id']/df_cluster['customer_id'].sum())

# Média Faturamento
df_media_faturamento = df[['faturamento', 'clusters']].groupby('clusters').mean().reset_index()
df_cluster = pd.merge(df_cluster, df_media_faturamento, how='inner', on="clusters")

# Média Recencia
df_media_faturamento = df[['recencia_days', 'clusters']].groupby('clusters').mean().reset_index()
df_cluster = pd.merge(df_cluster, df_media_faturamento, how='inner', on="clusters")

# Média Frequencia
df_media_faturamento = df[['invoice_no', 'clusters']].groupby('clusters').mean().reset_index()
df_cluster = pd.merge(df_cluster, df_media_faturamento, how='inner', on="clusters")

df_cluster

   clusters  customer_id  perc_customer  faturamento  recencia_days  invoice_no
0         0            6           0.14    182181.98           7.17       89.00
1         1         4335          99.15      1372.58          92.26        4.61
2         2           31           0.71     40543.52          13.29       53.29

Cluster 01: ( Candidato à Insider )
 - Número de customers: 6 (0,14% do customers)
 - Recência em média: 7 dias
 - Compras em média: 89 compras
 - Receita em média: $182.182,00 dólares

Cluster 02:
 - Número de customers: 31 (0,71% do customers)
 - Recência em média: 14 dias
 - Compras em média: 53 compras
 - Receita em média: $40.543,52 dólares

Cluster 03:
 - Número de customers: 4.335 (99% do customers)
 - Recência em média: 92 dias
 - Compras em média: 5 compras
 - Receita em média: $1.372,57 dólares